#pragma once

#include "5gone/types.hpp"

namespace gone {

class PuschEncoder {
public:
  explicit PuschEncoder(const AttackConfig& cfg);

  // Encode TB bytes into time-domain IQ for the given UL grant.
  SampleBuffer encode(const UlGrant& grant, const std::vector<uint8_t>& tb) const;

  // Load precomputed template IQ (generated by tools/generate_msg3_template.py).
  SampleBuffer load_template(const UlGrant& grant) const;

private:
  AttackConfig cfg_;
  SampleBuffer fallback_qpsk(const UlGrant& grant, const std::vector<uint8_t>& tb) const;
};

} // namespace gone
